name: SonarQube Executive Report
on:
  workflow_call:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Install Reporting Tool
        run: npm install -g sonar-report

      - name: Generate Sonar HTML Report
        run: |
          sonar-report \
            --sonarurl=${{ vars.SONAR_HOST_URL }} \
            --sonartoken="${{ secrets.SONAR_TOKEN }}" \
            --project=${{ secrets.SONAR_PROYECT_KEY }} \
            --sonarcomponent=${{ secrets.SONAR_PROYECT_KEY }} \
            --output="sonarq-report.html"

      - name: Upload Report to MinIO
        run: |
          # 1. Definición de variables
          REPO_NAME=${{ github.event.repository.name }}   
          CURRENT_DATE=$(date +'%Y-%m-%d')                
          FILE="sonarq-report.html"
          
          # 2. Descargar cliente MinIO
          curl -s https://dl.min.io/client/mc/release/linux-amd64/mc -o mc
          chmod +x mc
          
          # 3. Configurar alias
          ./mc alias set myminio ${{ vars.MINIO_HOST_URL }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
          
          # 4. Construir la ruta de destino (Sin la carpeta TOOL)
          TARGET_PATH="myminio/gitea-reports/${REPO_NAME}/${CURRENT_DATE}/${FILE}"
          
          echo "📤 Subiendo reporte: ${FILE}"
          echo "📂 Destino: ${REPO_NAME}/${CURRENT_DATE}/"
          
          # 5. Ejecutar la subida
          ./mc cp ${FILE} ${TARGET_PATH}
          
          if [ $? -eq 0 ]; then
            echo "✅ ¡Conseguido! Reporte subido a MinIO."
            echo "🔗 Ruta final: ${TARGET_PATH#myminio/}"
          else
            echo "❌ Error al subir a MinIO."
            exit 1
          fi